version: '3.2'
services:
  legacywebshop:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "8888:8080"
    networks:
      local_dev_net:
          aliases:
              - legacywebshop


networks:
  local_dev_net:
    driver: bridge
